repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: local
    hooks:
      - id: run-tests
        name: Run unit tests
        entry: pytest
        language: system
        always_run: true
        stages: [push]
